[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Hourly Building Data"
authors = [{name = "JB&B", email = "support@hourlybuildingdata.com"}]
dynamic = ["version", "description"]
